# Generated by Django 4.1.3 on 2022-12-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('ml', 'ml')], default='g', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Used_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('g', 'gram'), ('ml', 'ml')], default='g', max_length=4)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition_Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('polyunsaturated_fat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('monounsaturated_fat', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('trans_fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potassium', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('calcium', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('iron', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('zinc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dietary_fiber', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_a', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_d', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_e', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_k', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_b1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_b2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('niacin', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_b6', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_b12', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('folate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamin_c', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
            ],
        ),
    ]
