# Generated by Django 4.1.3 on 2022-12-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_facts',
            name='calories',
            field=models.DecimalField(decimal_places=2, help_text='熱量', max_digits=7),
        ),
    ]
