# Generated by Django 4.1.3 on 2022-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_nutrition_facts_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition_facts',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
