# Generated by Django 4.1.3 on 2023-01-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_rename_quantity_used_ingredient_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used_ingredient',
            name='serving',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
