# Generated by Django 4.1.3 on 2023-01-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_used_ingredient_serving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_ingredient',
            name='unit',
        ),
    ]
