# Generated by Django 4.1.3 on 2023-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_remove_used_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='used_ingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='used_ingredient',
            name='quantityUsed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='used_ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
