# Generated by Django 4.1.3 on 2023-01-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_used_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used_ingredient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='used_ingredient',
            name='quantityUsed',
        ),
        migrations.RemoveField(
            model_name='used_ingredient',
            name='unit',
        ),
    ]
