# Generated by Django 4.1.3 on 2023-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_alter_used_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
