# Generated by Django 4.1.3 on 2023-01-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0015_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient_file',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
