# Generated by Django 4.1.3 on 2022-12-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of the delicacy', max_length=50)),
                ('introduction', models.CharField(help_text='Enter a brief description of the recipe', max_length=1000)),
                ('delicacy_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('delicacy_type', models.CharField(choices=[('a', '開胃菜(appetizer)'), ('m', '主餐(main course)'), ('sf', '主食(staple food)'), ('sd', '副菜(side dish)'), ('d', '甜點(dessert)'), ('b', '飲品(beverages)')], default='a', max_length=5)),
                ('category', models.CharField(choices=[('m', '葷(meat)'), ('v', '純素(vegan)'), ('o', '蛋奶素(ovo-lacto vegetarian)'), ('f', '五辛素(Five pungent spices vegan)')], default='m', max_length=2)),
                ('cooking_time', models.PositiveIntegerField(blank=True, null=True)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('reference', models.CharField(blank=True, max_length=1000, null=True)),
                ('memo_text', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_method', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('step_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.recipe')),
            ],
        ),
    ]
