# Generated by Django 4.1.3 on 2023-01-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_delicacy_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Method',
            new_name='Step',
        ),
    ]
