# Generated by Django 4.1.3 on 2023-01-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_method_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='delicacy',
        ),
    ]
