# Generated by Django 4.1.3 on 2023-01-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_step_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='delicacy_photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/delicacy_photos'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_photo',
            field=models.ImageField(blank=True, null=True, upload_to='steps/step_photos'),
        ),
    ]
