# Generated by Django 4.1.3 on 2023-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_step_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
