# Generated by Django 4.1.3 on 2023-01-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_step_photo_step_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_photo',
        ),
    ]
