# Generated by Django 4.1.3 on 2023-01-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_step_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.step_photo'),
        ),
    ]
