# Generated by Django 4.1.3 on 2023-01-20 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_step_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/delicacy_photos')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='delicacy_photo',
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe_photo'),
        ),
    ]
