# Generated by Django 4.1.3 on 2023-01-30 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_photo_remove_recipe_delicacy_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
