# Generated by Django 4.1.3 on 2023-01-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_upload_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='upload_time',
            new_name='upload_date',
        ),
    ]
